### ISSUE TITLE
qunit-assert-close isn't compatible with QUnit v2.X anymore

### ISSUE THREAD

**Issue by Abszissex** [JamesMGreene/qunit-assert-close#8] opened 2016-09-16 06:57 UTC
The plugin isn't compatibel with QUnit v2.X.

![qunit error](https://cloud.githubusercontent.com/assets/4190798/18577668/7a75da68-7beb-11e6-9c4f-3ae75b8bf06f.PNG)

see the [upgrade guide to 2.X](http://qunitjs.com/upgrade-guide-2.x/)

**Comment by JamesMGreene** [comment] 2016-10-01 14:20
Fixed in 2dfc9e6. Published as `v2.1.0`. Thanks!

**Closed** 2016-10-01 14:20 UTC

**Comment by JamesMGreene** [comment] 2016-10-01 14:21
P.S. Basically a duplicate of #4.
